baseurl: "/tilix-web"

title: Tilix &colon; A tiling terminal emulator
author: Gerald Nunn
description: > # this means to ignore newlines until "baseurl:"
  Tilix is an advanced GTK3 tiling terminal for Linux based 
  on the Gnome Human Interface Guidelines (HIG).

gems: [jekyll-paginate]
# Number of articles per page
paginate: 9
paginate_path: "/news/page:num/"


sass:
  sass_dir: assets/sass
  style: :compressed

exclude: [README.md]
collections:
  features:
    output: false
  packages:
    output: false
  faqs:
    output: false
  manual:
    output: true
    permalink: /manual/:path/
